import type { Campaign, Candidate, FraudAlert, OrganizerAccount, PayoutRequest, PlatformStats, Transaction, VotePackage } from './types';

export const DEFAULT_VOTE_PACKAGES: VotePackage[] = [
  {
    id: 'pack-1',
    votes: 1,
    priceFCFA: 100,
    discountPercent: 0,
    label: '1 Vote',
  },
  {
    id: 'pack-5',
    votes: 5,
    priceFCFA: 500,
    discountPercent: 0,
    label: 'Pack Supporter (5x)',
  },
  {
    id: 'pack-10',
    votes: 10,
    priceFCFA: 900,
    discountPercent: 10,
    popular: true,
    label: 'Pack Populaire (10x)',
  },
  {
    id: 'pack-25',
    votes: 25,
    priceFCFA: 2125,
    discountPercent: 15,
    label: 'Pack Booster (25x)',
  },
  {
    id: 'pack-50',
    votes: 50,
    priceFCFA: 4000,
    discountPercent: 20,
    bestValue: true,
    label: 'Pack Champion (50x)',
  },
  {
    id: 'pack-100',
    votes: 100,
    priceFCFA: 7500,
    discountPercent: 25,
    label: 'Pack Méga Titan (100x)',
  },
];

export const INITIAL_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    name: 'Amina Diallo',
    category: 'Miss',
    number: 1,
    faculty: 'Informatique & Intelligence Artificielle',
    age: 21,
    bio: 'Passionnée de technologie, développeuse et fondatrice de l’initiative associative "Girls in Code Cameroon".',
    votes: 14820,
    percentage: 34.2,
    imageUrl: 'https://piponight-polytechnique.cm/backend/uploads/photo_6a49f4eee5b794.24498244.jpeg',
    quote: '« Autonomiser la jeunesse à travers le leadership technologique et l\'éthique. »',
    instagram: '@amina_diallo',
    rank: 1,
  },
  {
    id: 'cand-2',
    name: 'Koffi Mensah',
    category: 'Master',
    number: 2,
    faculty: 'Génie Biomédical',
    age: 23,
    bio: 'Futur chirurgien, pianiste classique et capitaine de l’équipe de débat universitaire.',
    votes: 12450,
    percentage: 28.7,
    imageUrl: 'https://piponight-polytechnique.cm/backend/uploads/photo_6a550f96571341.44832221.jpeg',
    quote: '« L\'excellence n\'est pas un acte, mais une habitude quotidienne au service de tous. »',
    instagram: '@koffi_mensah',
    rank: 2,
  },
  {
    id: 'cand-3',
    name: 'Grace Nkem',
    category: 'Miss',
    number: 3,
    faculty: 'Droit des Affaires & Éthique',
    age: 22,
    bio: 'Magistrate étudiante, oratrice primée et engagée dans l’accès aux soins en milieu rural.',
    votes: 9340,
    percentage: 21.5,
    imageUrl: 'https://piponight-polytechnique.cm/backend/uploads/photo_6a49f44dee4093.05822833.jpeg',
    quote: '« L\'intégrité dans le verbe, la justice dans l\'action et la bienveillance au quotidien. »',
    instagram: '@grace.nkem',
    rank: 3,
  },
  {
    id: 'cand-4',
    name: 'Yannick Tcham',
    category: 'Master',
    number: 4,
    faculty: 'Économie & Finance Durable',
    age: 22,
    bio: 'Jeune entrepreneur en agritech verte et ambassadeur du développement durable sur le campus.',
    votes: 6730,
    percentage: 15.6,
    imageUrl: 'https://piponight-polytechnique.cm/backend/uploads/photo_6a49f49e690689.60807830.jpeg',
    quote: '« Révolutionner l\'agriculture africaine grâce à l\'audace de la jeunesse. »',
    instagram: '@yannick_tcham',
    rank: 4,
  },
  {
    id: 'cand-5',
    name: 'Sara Benali',
    category: 'Prix Spécial du Public',
    number: 5,
    faculty: 'Architecture & Design Urbain',
    age: 21,
    bio: 'Designer d’espaces écologiques, artiste peintre et marathonienne.',
    votes: 4980,
    percentage: 11.5,
    imageUrl: 'https://piponight-polytechnique.cm/backend/uploads/photo_6a574381b104e9.28966654.jpeg',
    quote: '« Concevoir des espaces modernes et durables pour les générations futures. »',
    instagram: '@sara_benali_arch',
    rank: 5,
  },
  {
    id: 'cand-6',
    name: 'David Osei',
    category: 'Prix Spécial du Public',
    number: 6,
    faculty: 'Sciences Aéronautiques',
    age: 24,
    bio: 'Chercheur en robotique de drones et mentor pour les lycéens dans les filières STEM.',
    votes: 4120,
    percentage: 9.5,
    imageUrl: 'https://piponight-polytechnique.cm/backend/uploads/photo_6a5516258f1096.97480550.jpeg',
    quote: '« Le ciel n\'est pas la limite, c\'est seulement notre point de départ. »',
    instagram: '@david_aero',
    rank: 6,
  },
];

export const INITIAL_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    title: 'Élection Miss & Master UY1 2026',
    subtitle: 'Grande Finale Annuelle de l\'Excellence, du Charisme et du Leadership Académique',
    organization: 'Comité Miss & Master UY1 (Conseil Étudiant)',
    organizerId: 'org-1',
    category: 'Concours Universitaire & Élection',
    categories: ['Miss', 'Master', 'Prix Spécial du Public'],
    bannerUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1400&auto=format&fit=crop&q=80',
    startDate: '2026-08-15',
    endDate: '2026-09-02T23:59:59',
    status: 'active',
    totalVotes: 52440,
    totalRevenueFCFA: 5244000,
    pricePerVoteFCFA: 100,
    candidates: INITIAL_CANDIDATES,
    allowPublicStats: true,
  },
  {
    id: 'camp-2',
    title: 'AfroTech Pitch Awards 2026',
    subtitle: 'Prix du Public pour les Meilleurs Startuppers et Innovateurs Africains',
    organization: 'Silicon Savanna Hub',
    organizerId: 'org-2',
    category: 'Innovation & Startups',
    categories: ['Tech', 'Agritech', 'Green Energy'],
    bannerUrl: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1400&auto=format&fit=crop&q=80',
    startDate: '2026-08-01',
    endDate: '2026-09-10T23:59:59',
    status: 'active',
    totalVotes: 28410,
    totalRevenueFCFA: 2841000,
    pricePerVoteFCFA: 100,
    candidates: [],
    allowPublicStats: true,
  },
  {
    id: 'camp-3',
    title: 'Indie Sound Africa Awards',
    subtitle: 'Vote officiel du Meilleur Artiste Révélation Vocale & Musique Urbaine',
    organization: 'AfroBeats Foundation',
    organizerId: 'org-3',
    category: 'Musique & Culture',
    categories: ['Révélation Féminine', 'Révélation Masculine', 'Meilleur Clip'],
    bannerUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1400&auto=format&fit=crop&q=80',
    startDate: '2026-07-20',
    endDate: '2026-08-30T23:59:59',
    status: 'active',
    totalVotes: 71200,
    totalRevenueFCFA: 7120000,
    pricePerVoteFCFA: 100,
    candidates: [],
    allowPublicStats: true,
  },
];

export const INITIAL_ORGANIZERS: OrganizerAccount[] = [
  {
    id: 'org-1',
    name: 'Pr. Marcelle Ebongue',
    organization: 'Comité Miss & Master UY1 (Conseil Étudiant)',
    email: 'contact@uy1-events.cm',
    phone: '+237 677 00 22 11',
    status: 'active',
    campaignsCount: 2,
    totalRaisedFCFA: 5244000,
    joinedDate: '12 Jan 2026',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'org-2',
    name: 'Ibrahim Touré',
    organization: 'Silicon Savanna Hub SARL',
    email: 'treasury@siliconsavanna.africa',
    phone: '+225 07 88 90 12',
    status: 'active',
    campaignsCount: 1,
    totalRaisedFCFA: 2841000,
    joinedDate: '04 Fév 2026',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'org-3',
    name: 'Samuel Ndione',
    organization: 'AfroBeats Foundation Events',
    email: 'ops@afrobeatsfoundation.org',
    phone: '+221 77 450 12 34',
    status: 'active',
    campaignsCount: 3,
    totalRaisedFCFA: 7120000,
    joinedDate: '18 Nov 2025',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&auto=format&fit=crop&q=80',
  },
  {
    id: 'org-4',
    name: 'Henriette Talla',
    organization: 'Lycée Classique Arts Club',
    email: 'arts@lyceeclassique.org',
    phone: '+237 690 12 34 56',
    status: 'suspended',
    campaignsCount: 1,
    totalRaisedFCFA: 750000,
    joinedDate: '10 Mars 2026',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-101',
    transactionRef: 'IVT-89201',
    voterName: 'Michel Fopa',
    voterPhone: '+237 699 •• •• 12',
    candidateId: 'cand-1',
    candidateName: 'Amina Diallo',
    candidateCategory: 'Miss',
    candidateAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    votesCount: 50,
    amountFCFA: 4000,
    paymentMethod: 'orange_money',
    status: 'completed',
    timestamp: 'Il y a 2 min',
    message: 'Tout mon soutien Amina, continue d\'inspirer les jeunes filles !',
  },
  {
    id: 'tx-102',
    transactionRef: 'IVT-89200',
    voterName: 'Danielle Tchouassi',
    voterPhone: '+237 677 •• •• 99',
    candidateId: 'cand-2',
    candidateName: 'Koffi Mensah',
    candidateCategory: 'Master',
    candidateAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    votesCount: 100,
    amountFCFA: 7500,
    paymentMethod: 'mtn_momo',
    status: 'completed',
    timestamp: 'Il y a 7 min',
    message: 'Fiers de notre capitaine en Biomédical ! Victoire assurée !',
  },
  {
    id: 'tx-103',
    transactionRef: 'IVT-89199',
    voterName: 'Supporter Anonyme',
    voterPhone: '+225 07 •• •• 12',
    candidateId: 'cand-3',
    candidateName: 'Grace Nkem',
    candidateCategory: 'Miss',
    candidateAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    votesCount: 25,
    amountFCFA: 2125,
    paymentMethod: 'orange_money',
    status: 'completed',
    timestamp: 'Il y a 14 min',
  },
  {
    id: 'tx-104',
    transactionRef: 'IVT-89198',
    voterName: 'Bertrand Ewane',
    voterPhone: '+237 650 •• •• 22',
    candidateId: 'cand-4',
    candidateName: 'Yannick Tcham',
    candidateCategory: 'Master',
    candidateAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    votesCount: 10,
    amountFCFA: 900,
    paymentMethod: 'mtn_momo',
    status: 'completed',
    timestamp: 'Il y a 28 min',
    message: 'L\'agritech verte en avant !',
  },
  {
    id: 'tx-105',
    transactionRef: 'IVT-89197',
    voterName: 'Cynthia Ndongo',
    voterPhone: '+237 690 •• •• 00',
    candidateId: 'cand-1',
    candidateName: 'Amina Diallo',
    candidateCategory: 'Miss',
    candidateAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    votesCount: 10,
    amountFCFA: 900,
    paymentMethod: 'orange_money',
    status: 'completed',
    timestamp: 'Il y a 42 min',
  },
  {
    id: 'tx-106',
    transactionRef: 'IVT-89196',
    voterName: 'Boris Kamga',
    voterPhone: '+237 671 •• •• 77',
    candidateId: 'cand-5',
    candidateName: 'Sara Benali',
    candidateCategory: 'Prix Spécial du Public',
    candidateAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    votesCount: 5,
    amountFCFA: 450,
    paymentMethod: 'mtn_momo',
    status: 'completed',
    timestamp: 'Il y a 1 heure',
  },
];

export const INITIAL_PAYOUTS: PayoutRequest[] = [
  {
    id: 'po-301',
    organizerId: 'org-1',
    organizerName: 'Comité Miss & Master UY1 (Conseil Étudiant)',
    organizerEmail: 'contact@uy1-events.cm',
    organizerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    campaignId: 'camp-1',
    campaignTitle: 'Élection Miss & Master UY1 2026',
    requestedAmountFCFA: 3500000,
    commissionFeeFCFA: 350000,
    netPayoutFCFA: 3150000,
    paymentMethod: 'mtn_momo',
    walletNumber: '+237 677 00 22 11 (Compte Marchand Pro)',
    status: 'pending',
    requestedAt: 'Aujourd\'hui à 14:32',
  },
  {
    id: 'po-302',
    organizerId: 'org-2',
    organizerName: 'Silicon Savanna Hub SARL',
    organizerEmail: 'treasury@siliconsavanna.africa',
    organizerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    campaignId: 'camp-2',
    campaignTitle: 'AfroTech Pitch Awards 2026',
    requestedAmountFCFA: 2000000,
    commissionFeeFCFA: 200000,
    netPayoutFCFA: 1800000,
    paymentMethod: 'orange_money',
    walletNumber: '+237 699 44 88 55',
    status: 'pending',
    requestedAt: 'Hier à 18:15',
  },
  {
    id: 'po-303',
    organizerId: 'org-3',
    organizerName: 'AfroBeats Foundation Events',
    organizerEmail: 'ops@afrobeatsfoundation.org',
    organizerAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&auto=format&fit=crop&q=80',
    campaignId: 'camp-3',
    campaignTitle: 'Indie Sound Africa Awards',
    requestedAmountFCFA: 5000000,
    commissionFeeFCFA: 500000,
    netPayoutFCFA: 4500000,
    paymentMethod: 'bank_transfer',
    walletNumber: 'Banque UBA •••• 9104 (IBAN CM21...)',
    status: 'approved',
    requestedAt: 'Il y a 3 jours',
    processedAt: 'Il y a 2 jours par Direction IVote',
  },
  {
    id: 'po-304',
    organizerId: 'org-4',
    organizerName: 'Lycée Classique Arts Club',
    organizerEmail: 'arts@lyceeclassique.org',
    organizerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    campaignId: 'camp-4',
    campaignTitle: 'Trophée des Talents Inter-Lycées',
    requestedAmountFCFA: 750000,
    commissionFeeFCFA: 75000,
    netPayoutFCFA: 675000,
    paymentMethod: 'orange_money',
    walletNumber: '+225 05 12 34 56',
    status: 'rejected',
    requestedAt: 'Il y a 4 jours',
    processedAt: 'Il y a 3 jours',
    rejectionReason: 'Attestation fiscale et pièce d\'identité du représentant légal non conformes.',
  },
];

export const INITIAL_FRAUD_ALERTS: FraudAlert[] = [
  {
    id: 'fa-1',
    severity: 'medium',
    campaignTitle: 'Élection Miss & Master UY1 2026',
    candidateName: 'Koffi Mensah',
    description: 'Pic inhabituel de 8 transactions de 100 votes en moins de 90 secondes depuis la même plage IP Orange Money.',
    detectedAt: 'Il y a 18 min',
    status: 'open',
    ipOrPhone: '197.234.12.88 / +237 699 •• •• 45',
  },
  {
    id: 'fa-2',
    severity: 'low',
    campaignTitle: 'AfroTech Pitch Awards 2026',
    candidateName: 'Startup PayFast',
    description: '3 échecs successifs de saisie de code PIN USSD sur portefeuille MTN MoMo.',
    detectedAt: 'Il y a 1h 10min',
    status: 'resolved',
    ipOrPhone: '+237 677 •• •• 19',
  },
];

export const INITIAL_PLATFORM_STATS: PlatformStats = {
  totalPlatformVolumeFCFA: 48950000,
  totalVotesCast: 489500,
  totalOrganizers: 142,
  activeCampaignsCount: 18,
  globalCommissionPercent: 10,
  totalCommissionEarnedFCFA: 4895000,
  avgOrderValueFCFA: 1850,
};
